//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceManReceta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Receta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TratamientosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRecetaField, value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Medicamentos {
            get {
                return this.MedicamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicamentosField, value) != true)) {
                    this.MedicamentosField = value;
                    this.RaisePropertyChanged("Medicamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tratamientos {
            get {
                return this.TratamientosField;
            }
            set {
                if ((object.ReferenceEquals(this.TratamientosField, value) != true)) {
                    this.TratamientosField = value;
                    this.RaisePropertyChanged("Tratamientos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceManReceta.WebServiceMantenedorRecetaSoap")]
    public interface WebServiceMantenedorRecetaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento receta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarReceta", ReplyAction="*")]
        CapaGUI.ServiceManReceta.webGuardarRecetaResponse webGuardarReceta(CapaGUI.ServiceManReceta.webGuardarRecetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarReceta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManReceta.webGuardarRecetaResponse> webGuardarRecetaAsync(CapaGUI.ServiceManReceta.webGuardarRecetaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idControl del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webCambiarEstadoConsulta", ReplyAction="*")]
        CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponse webCambiarEstadoConsulta(CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webCambiarEstadoConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponse> webCambiarEstadoConsultaAsync(CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webGuardarRecetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webGuardarReceta", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManReceta.webGuardarRecetaRequestBody Body;
        
        public webGuardarRecetaRequest() {
        }
        
        public webGuardarRecetaRequest(CapaGUI.ServiceManReceta.webGuardarRecetaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webGuardarRecetaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceManReceta.Receta receta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idControl;
        
        public webGuardarRecetaRequestBody() {
        }
        
        public webGuardarRecetaRequestBody(CapaGUI.ServiceManReceta.Receta receta, string idControl) {
            this.receta = receta;
            this.idControl = idControl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webGuardarRecetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webGuardarRecetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManReceta.webGuardarRecetaResponseBody Body;
        
        public webGuardarRecetaResponse() {
        }
        
        public webGuardarRecetaResponse(CapaGUI.ServiceManReceta.webGuardarRecetaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webGuardarRecetaResponseBody {
        
        public webGuardarRecetaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webCambiarEstadoConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webCambiarEstadoConsulta", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequestBody Body;
        
        public webCambiarEstadoConsultaRequest() {
        }
        
        public webCambiarEstadoConsultaRequest(CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webCambiarEstadoConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rut;
        
        public webCambiarEstadoConsultaRequestBody() {
        }
        
        public webCambiarEstadoConsultaRequestBody(string idControl, string rut) {
            this.idControl = idControl;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webCambiarEstadoConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webCambiarEstadoConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponseBody Body;
        
        public webCambiarEstadoConsultaResponse() {
        }
        
        public webCambiarEstadoConsultaResponse(CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webCambiarEstadoConsultaResponseBody {
        
        public webCambiarEstadoConsultaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorRecetaSoapChannel : CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorRecetaSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap>, CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap {
        
        public WebServiceMantenedorRecetaSoapClient() {
        }
        
        public WebServiceMantenedorRecetaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorRecetaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorRecetaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorRecetaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManReceta.webGuardarRecetaResponse CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap.webGuardarReceta(CapaGUI.ServiceManReceta.webGuardarRecetaRequest request) {
            return base.Channel.webGuardarReceta(request);
        }
        
        public void webGuardarReceta(CapaGUI.ServiceManReceta.Receta receta, string idControl) {
            CapaGUI.ServiceManReceta.webGuardarRecetaRequest inValue = new CapaGUI.ServiceManReceta.webGuardarRecetaRequest();
            inValue.Body = new CapaGUI.ServiceManReceta.webGuardarRecetaRequestBody();
            inValue.Body.receta = receta;
            inValue.Body.idControl = idControl;
            CapaGUI.ServiceManReceta.webGuardarRecetaResponse retVal = ((CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap)(this)).webGuardarReceta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManReceta.webGuardarRecetaResponse> CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap.webGuardarRecetaAsync(CapaGUI.ServiceManReceta.webGuardarRecetaRequest request) {
            return base.Channel.webGuardarRecetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManReceta.webGuardarRecetaResponse> webGuardarRecetaAsync(CapaGUI.ServiceManReceta.Receta receta, string idControl) {
            CapaGUI.ServiceManReceta.webGuardarRecetaRequest inValue = new CapaGUI.ServiceManReceta.webGuardarRecetaRequest();
            inValue.Body = new CapaGUI.ServiceManReceta.webGuardarRecetaRequestBody();
            inValue.Body.receta = receta;
            inValue.Body.idControl = idControl;
            return ((CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap)(this)).webGuardarRecetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponse CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap.webCambiarEstadoConsulta(CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest request) {
            return base.Channel.webCambiarEstadoConsulta(request);
        }
        
        public void webCambiarEstadoConsulta(string idControl, string rut) {
            CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest inValue = new CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest();
            inValue.Body = new CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequestBody();
            inValue.Body.idControl = idControl;
            inValue.Body.rut = rut;
            CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponse retVal = ((CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap)(this)).webCambiarEstadoConsulta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponse> CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap.webCambiarEstadoConsultaAsync(CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest request) {
            return base.Channel.webCambiarEstadoConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManReceta.webCambiarEstadoConsultaResponse> webCambiarEstadoConsultaAsync(string idControl, string rut) {
            CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest inValue = new CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequest();
            inValue.Body = new CapaGUI.ServiceManReceta.webCambiarEstadoConsultaRequestBody();
            inValue.Body.idControl = idControl;
            inValue.Body.rut = rut;
            return ((CapaGUI.ServiceManReceta.WebServiceMantenedorRecetaSoap)(this)).webCambiarEstadoConsultaAsync(inValue);
        }
    }
}
