//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceManMedico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medico", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Medico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuxRutMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        private int SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuxRutM {
            get {
                return this.AuxRutMField;
            }
            set {
                if ((object.ReferenceEquals(this.AuxRutMField, value) != true)) {
                    this.AuxRutMField = value;
                    this.RaisePropertyChanged("AuxRutM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceManMedico.WebServiceMantenedorMedicoSoap")]
    public interface WebServiceMantenedorMedicoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarMedico", ReplyAction="*")]
        CapaGUI.ServiceManMedico.webBuscarMedicoResponse webBuscarMedico(CapaGUI.ServiceManMedico.webBuscarMedicoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarMedico", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManMedico.webBuscarMedicoResponse> webBuscarMedicoAsync(CapaGUI.ServiceManMedico.webBuscarMedicoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarNombresMedico", ReplyAction="*")]
        CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponse webBuscarNombresMedico(CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarNombresMedico", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponse> webBuscarNombresMedicoAsync(CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webBuscarMedicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webBuscarMedico", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManMedico.webBuscarMedicoRequestBody Body;
        
        public webBuscarMedicoRequest() {
        }
        
        public webBuscarMedicoRequest(CapaGUI.ServiceManMedico.webBuscarMedicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webBuscarMedicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public webBuscarMedicoRequestBody() {
        }
        
        public webBuscarMedicoRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webBuscarMedicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webBuscarMedicoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManMedico.webBuscarMedicoResponseBody Body;
        
        public webBuscarMedicoResponse() {
        }
        
        public webBuscarMedicoResponse(CapaGUI.ServiceManMedico.webBuscarMedicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webBuscarMedicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceManMedico.Medico webBuscarMedicoResult;
        
        public webBuscarMedicoResponseBody() {
        }
        
        public webBuscarMedicoResponseBody(CapaGUI.ServiceManMedico.Medico webBuscarMedicoResult) {
            this.webBuscarMedicoResult = webBuscarMedicoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webBuscarNombresMedicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webBuscarNombresMedico", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequestBody Body;
        
        public webBuscarNombresMedicoRequest() {
        }
        
        public webBuscarNombresMedicoRequest(CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webBuscarNombresMedicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public webBuscarNombresMedicoRequestBody() {
        }
        
        public webBuscarNombresMedicoRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webBuscarNombresMedicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webBuscarNombresMedicoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponseBody Body;
        
        public webBuscarNombresMedicoResponse() {
        }
        
        public webBuscarNombresMedicoResponse(CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webBuscarNombresMedicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceManMedico.Medico webBuscarNombresMedicoResult;
        
        public webBuscarNombresMedicoResponseBody() {
        }
        
        public webBuscarNombresMedicoResponseBody(CapaGUI.ServiceManMedico.Medico webBuscarNombresMedicoResult) {
            this.webBuscarNombresMedicoResult = webBuscarNombresMedicoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorMedicoSoapChannel : CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorMedicoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap>, CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap {
        
        public WebServiceMantenedorMedicoSoapClient() {
        }
        
        public WebServiceMantenedorMedicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorMedicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorMedicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorMedicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManMedico.webBuscarMedicoResponse CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap.webBuscarMedico(CapaGUI.ServiceManMedico.webBuscarMedicoRequest request) {
            return base.Channel.webBuscarMedico(request);
        }
        
        public CapaGUI.ServiceManMedico.Medico webBuscarMedico(string rut) {
            CapaGUI.ServiceManMedico.webBuscarMedicoRequest inValue = new CapaGUI.ServiceManMedico.webBuscarMedicoRequest();
            inValue.Body = new CapaGUI.ServiceManMedico.webBuscarMedicoRequestBody();
            inValue.Body.rut = rut;
            CapaGUI.ServiceManMedico.webBuscarMedicoResponse retVal = ((CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap)(this)).webBuscarMedico(inValue);
            return retVal.Body.webBuscarMedicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManMedico.webBuscarMedicoResponse> CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap.webBuscarMedicoAsync(CapaGUI.ServiceManMedico.webBuscarMedicoRequest request) {
            return base.Channel.webBuscarMedicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManMedico.webBuscarMedicoResponse> webBuscarMedicoAsync(string rut) {
            CapaGUI.ServiceManMedico.webBuscarMedicoRequest inValue = new CapaGUI.ServiceManMedico.webBuscarMedicoRequest();
            inValue.Body = new CapaGUI.ServiceManMedico.webBuscarMedicoRequestBody();
            inValue.Body.rut = rut;
            return ((CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap)(this)).webBuscarMedicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponse CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap.webBuscarNombresMedico(CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest request) {
            return base.Channel.webBuscarNombresMedico(request);
        }
        
        public CapaGUI.ServiceManMedico.Medico webBuscarNombresMedico(string rut) {
            CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest inValue = new CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest();
            inValue.Body = new CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequestBody();
            inValue.Body.rut = rut;
            CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponse retVal = ((CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap)(this)).webBuscarNombresMedico(inValue);
            return retVal.Body.webBuscarNombresMedicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponse> CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap.webBuscarNombresMedicoAsync(CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest request) {
            return base.Channel.webBuscarNombresMedicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManMedico.webBuscarNombresMedicoResponse> webBuscarNombresMedicoAsync(string rut) {
            CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest inValue = new CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequest();
            inValue.Body = new CapaGUI.ServiceManMedico.webBuscarNombresMedicoRequestBody();
            inValue.Body.rut = rut;
            return ((CapaGUI.ServiceManMedico.WebServiceMantenedorMedicoSoap)(this)).webBuscarNombresMedicoAsync(inValue);
        }
    }
}
