//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceManPaciente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrevisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RutP {
            get {
                return this.RutPField;
            }
            set {
                if ((object.ReferenceEquals(this.RutPField, value) != true)) {
                    this.RutPField = value;
                    this.RaisePropertyChanged("RutP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PNombre {
            get {
                return this.PNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PNombreField, value) != true)) {
                    this.PNombreField = value;
                    this.RaisePropertyChanged("PNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SNombre {
            get {
                return this.SNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SNombreField, value) != true)) {
                    this.SNombreField = value;
                    this.RaisePropertyChanged("SNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ApellidoP {
            get {
                return this.ApellidoPField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPField, value) != true)) {
                    this.ApellidoPField = value;
                    this.RaisePropertyChanged("ApellidoP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApellidoM {
            get {
                return this.ApellidoMField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMField, value) != true)) {
                    this.ApellidoMField = value;
                    this.RaisePropertyChanged("ApellidoM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Anos {
            get {
                return this.AnosField;
            }
            set {
                if ((object.ReferenceEquals(this.AnosField, value) != true)) {
                    this.AnosField = value;
                    this.RaisePropertyChanged("Anos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Prevision {
            get {
                return this.PrevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.PrevisionField, value) != true)) {
                    this.PrevisionField = value;
                    this.RaisePropertyChanged("Prevision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceManPaciente.WebServiceMantenedorPacienteSoap")]
    public interface WebServiceMantenedorPacienteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento paciente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarPaciente", ReplyAction="*")]
        CapaGUI.ServiceManPaciente.webGuardarPacienteResponse webGuardarPaciente(CapaGUI.ServiceManPaciente.webGuardarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManPaciente.webGuardarPacienteResponse> webGuardarPacienteAsync(CapaGUI.ServiceManPaciente.webGuardarPacienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarPaciente", ReplyAction="*")]
        CapaGUI.ServiceManPaciente.webBuscarPacienteResponse webBuscarPaciente(CapaGUI.ServiceManPaciente.webBuscarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManPaciente.webBuscarPacienteResponse> webBuscarPacienteAsync(CapaGUI.ServiceManPaciente.webBuscarPacienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webGuardarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webGuardarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManPaciente.webGuardarPacienteRequestBody Body;
        
        public webGuardarPacienteRequest() {
        }
        
        public webGuardarPacienteRequest(CapaGUI.ServiceManPaciente.webGuardarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webGuardarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceManPaciente.Paciente paciente;
        
        public webGuardarPacienteRequestBody() {
        }
        
        public webGuardarPacienteRequestBody(CapaGUI.ServiceManPaciente.Paciente paciente) {
            this.paciente = paciente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webGuardarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webGuardarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManPaciente.webGuardarPacienteResponseBody Body;
        
        public webGuardarPacienteResponse() {
        }
        
        public webGuardarPacienteResponse(CapaGUI.ServiceManPaciente.webGuardarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webGuardarPacienteResponseBody {
        
        public webGuardarPacienteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webBuscarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webBuscarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManPaciente.webBuscarPacienteRequestBody Body;
        
        public webBuscarPacienteRequest() {
        }
        
        public webBuscarPacienteRequest(CapaGUI.ServiceManPaciente.webBuscarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webBuscarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public webBuscarPacienteRequestBody() {
        }
        
        public webBuscarPacienteRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webBuscarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webBuscarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManPaciente.webBuscarPacienteResponseBody Body;
        
        public webBuscarPacienteResponse() {
        }
        
        public webBuscarPacienteResponse(CapaGUI.ServiceManPaciente.webBuscarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webBuscarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceManPaciente.Paciente webBuscarPacienteResult;
        
        public webBuscarPacienteResponseBody() {
        }
        
        public webBuscarPacienteResponseBody(CapaGUI.ServiceManPaciente.Paciente webBuscarPacienteResult) {
            this.webBuscarPacienteResult = webBuscarPacienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorPacienteSoapChannel : CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorPacienteSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap>, CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap {
        
        public WebServiceMantenedorPacienteSoapClient() {
        }
        
        public WebServiceMantenedorPacienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorPacienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorPacienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorPacienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManPaciente.webGuardarPacienteResponse CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap.webGuardarPaciente(CapaGUI.ServiceManPaciente.webGuardarPacienteRequest request) {
            return base.Channel.webGuardarPaciente(request);
        }
        
        public void webGuardarPaciente(CapaGUI.ServiceManPaciente.Paciente paciente) {
            CapaGUI.ServiceManPaciente.webGuardarPacienteRequest inValue = new CapaGUI.ServiceManPaciente.webGuardarPacienteRequest();
            inValue.Body = new CapaGUI.ServiceManPaciente.webGuardarPacienteRequestBody();
            inValue.Body.paciente = paciente;
            CapaGUI.ServiceManPaciente.webGuardarPacienteResponse retVal = ((CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap)(this)).webGuardarPaciente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManPaciente.webGuardarPacienteResponse> CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap.webGuardarPacienteAsync(CapaGUI.ServiceManPaciente.webGuardarPacienteRequest request) {
            return base.Channel.webGuardarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManPaciente.webGuardarPacienteResponse> webGuardarPacienteAsync(CapaGUI.ServiceManPaciente.Paciente paciente) {
            CapaGUI.ServiceManPaciente.webGuardarPacienteRequest inValue = new CapaGUI.ServiceManPaciente.webGuardarPacienteRequest();
            inValue.Body = new CapaGUI.ServiceManPaciente.webGuardarPacienteRequestBody();
            inValue.Body.paciente = paciente;
            return ((CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap)(this)).webGuardarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManPaciente.webBuscarPacienteResponse CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap.webBuscarPaciente(CapaGUI.ServiceManPaciente.webBuscarPacienteRequest request) {
            return base.Channel.webBuscarPaciente(request);
        }
        
        public CapaGUI.ServiceManPaciente.Paciente webBuscarPaciente(string rut) {
            CapaGUI.ServiceManPaciente.webBuscarPacienteRequest inValue = new CapaGUI.ServiceManPaciente.webBuscarPacienteRequest();
            inValue.Body = new CapaGUI.ServiceManPaciente.webBuscarPacienteRequestBody();
            inValue.Body.rut = rut;
            CapaGUI.ServiceManPaciente.webBuscarPacienteResponse retVal = ((CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap)(this)).webBuscarPaciente(inValue);
            return retVal.Body.webBuscarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManPaciente.webBuscarPacienteResponse> CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap.webBuscarPacienteAsync(CapaGUI.ServiceManPaciente.webBuscarPacienteRequest request) {
            return base.Channel.webBuscarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManPaciente.webBuscarPacienteResponse> webBuscarPacienteAsync(string rut) {
            CapaGUI.ServiceManPaciente.webBuscarPacienteRequest inValue = new CapaGUI.ServiceManPaciente.webBuscarPacienteRequest();
            inValue.Body = new CapaGUI.ServiceManPaciente.webBuscarPacienteRequestBody();
            inValue.Body.rut = rut;
            return ((CapaGUI.ServiceManPaciente.WebServiceMantenedorPacienteSoap)(this)).webBuscarPacienteAsync(inValue);
        }
    }
}
