//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceManDiagnostico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Diagnostico", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Diagnostico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDiagnosticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosticoConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDiagnosticoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdDiagnostico {
            get {
                return this.IdDiagnosticoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDiagnosticoField, value) != true)) {
                    this.IdDiagnosticoField = value;
                    this.RaisePropertyChanged("IdDiagnostico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DiagnosticoConsulta {
            get {
                return this.DiagnosticoConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosticoConsultaField, value) != true)) {
                    this.DiagnosticoConsultaField = value;
                    this.RaisePropertyChanged("DiagnosticoConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoDiagnostico {
            get {
                return this.TipoDiagnosticoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDiagnosticoField, value) != true)) {
                    this.TipoDiagnosticoField = value;
                    this.RaisePropertyChanged("TipoDiagnostico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap")]
    public interface WebServiceMantenedorDiagnosticoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento diagnostico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarDiagnostico", ReplyAction="*")]
        CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponse webGuardarDiagnostico(CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarDiagnostico", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponse> webGuardarDiagnosticoAsync(CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idControl del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webCambiarEstadoConsulta", ReplyAction="*")]
        CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponse webCambiarEstadoConsulta(CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webCambiarEstadoConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponse> webCambiarEstadoConsultaAsync(CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webGuardarDiagnosticoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webGuardarDiagnostico", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequestBody Body;
        
        public webGuardarDiagnosticoRequest() {
        }
        
        public webGuardarDiagnosticoRequest(CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webGuardarDiagnosticoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceManDiagnostico.Diagnostico diagnostico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipoDiagnostico;
        
        public webGuardarDiagnosticoRequestBody() {
        }
        
        public webGuardarDiagnosticoRequestBody(CapaGUI.ServiceManDiagnostico.Diagnostico diagnostico, string idControl, string tipoDiagnostico) {
            this.diagnostico = diagnostico;
            this.idControl = idControl;
            this.tipoDiagnostico = tipoDiagnostico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webGuardarDiagnosticoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webGuardarDiagnosticoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponseBody Body;
        
        public webGuardarDiagnosticoResponse() {
        }
        
        public webGuardarDiagnosticoResponse(CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webGuardarDiagnosticoResponseBody {
        
        public webGuardarDiagnosticoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webCambiarEstadoConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webCambiarEstadoConsulta", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequestBody Body;
        
        public webCambiarEstadoConsultaRequest() {
        }
        
        public webCambiarEstadoConsultaRequest(CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webCambiarEstadoConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rut;
        
        public webCambiarEstadoConsultaRequestBody() {
        }
        
        public webCambiarEstadoConsultaRequestBody(string idControl, string rut) {
            this.idControl = idControl;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webCambiarEstadoConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webCambiarEstadoConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponseBody Body;
        
        public webCambiarEstadoConsultaResponse() {
        }
        
        public webCambiarEstadoConsultaResponse(CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webCambiarEstadoConsultaResponseBody {
        
        public webCambiarEstadoConsultaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorDiagnosticoSoapChannel : CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorDiagnosticoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap>, CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap {
        
        public WebServiceMantenedorDiagnosticoSoapClient() {
        }
        
        public WebServiceMantenedorDiagnosticoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorDiagnosticoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDiagnosticoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorDiagnosticoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponse CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap.webGuardarDiagnostico(CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest request) {
            return base.Channel.webGuardarDiagnostico(request);
        }
        
        public void webGuardarDiagnostico(CapaGUI.ServiceManDiagnostico.Diagnostico diagnostico, string idControl, string tipoDiagnostico) {
            CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest inValue = new CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest();
            inValue.Body = new CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequestBody();
            inValue.Body.diagnostico = diagnostico;
            inValue.Body.idControl = idControl;
            inValue.Body.tipoDiagnostico = tipoDiagnostico;
            CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponse retVal = ((CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap)(this)).webGuardarDiagnostico(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponse> CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap.webGuardarDiagnosticoAsync(CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest request) {
            return base.Channel.webGuardarDiagnosticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoResponse> webGuardarDiagnosticoAsync(CapaGUI.ServiceManDiagnostico.Diagnostico diagnostico, string idControl, string tipoDiagnostico) {
            CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest inValue = new CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequest();
            inValue.Body = new CapaGUI.ServiceManDiagnostico.webGuardarDiagnosticoRequestBody();
            inValue.Body.diagnostico = diagnostico;
            inValue.Body.idControl = idControl;
            inValue.Body.tipoDiagnostico = tipoDiagnostico;
            return ((CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap)(this)).webGuardarDiagnosticoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponse CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap.webCambiarEstadoConsulta(CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest request) {
            return base.Channel.webCambiarEstadoConsulta(request);
        }
        
        public void webCambiarEstadoConsulta(string idControl, string rut) {
            CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest inValue = new CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest();
            inValue.Body = new CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequestBody();
            inValue.Body.idControl = idControl;
            inValue.Body.rut = rut;
            CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponse retVal = ((CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap)(this)).webCambiarEstadoConsulta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponse> CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap.webCambiarEstadoConsultaAsync(CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest request) {
            return base.Channel.webCambiarEstadoConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaResponse> webCambiarEstadoConsultaAsync(string idControl, string rut) {
            CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest inValue = new CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequest();
            inValue.Body = new CapaGUI.ServiceManDiagnostico.webCambiarEstadoConsultaRequestBody();
            inValue.Body.idControl = idControl;
            inValue.Body.rut = rut;
            return ((CapaGUI.ServiceManDiagnostico.WebServiceMantenedorDiagnosticoSoap)(this)).webCambiarEstadoConsultaAsync(inValue);
        }
    }
}
