//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceManControl {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceManControl.WebServiceMantenedorControlSoap")]
    public interface WebServiceMantenedorControlSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webGuardarControl(CapaGUI.ServiceManControl.Control control, string rutP, string rutM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarControl", ReplyAction="*")]
        System.Threading.Tasks.Task webGuardarControlAsync(CapaGUI.ServiceManControl.Control control, string rutP, string rutM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarHistorial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webListarHistorial(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarHistorial", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webListarHistorialAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivosPantalla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceManControl.Control webListarActivosPantalla(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivosPantalla", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManControl.Control> webListarActivosPantallaAsync(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivosPantallaReceta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceManControl.Control webListarActivosPantallaReceta(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivosPantallaReceta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceManControl.Control> webListarActivosPantallaRecetaAsync(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webListarActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webListarActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivosReceta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webListarActivosReceta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarActivosReceta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webListarActivosRecetaAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Control : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idControlField;
        
        private string causaField;
        
        private string prioridadField;
        
        private string frecuenciaCardiacaField;
        
        private string frecuenciaRespiratoriaField;
        
        private string presionArterialField;
        
        private string saturacionO2Field;
        
        private string temperaturaField;
        
        private string dolorField;
        
        private System.DateTime fechaField;
        
        private string estadoField;
        
        private Paciente auxPacienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdControl {
            get {
                return this.idControlField;
            }
            set {
                this.idControlField = value;
                this.RaisePropertyChanged("IdControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Causa {
            get {
                return this.causaField;
            }
            set {
                this.causaField = value;
                this.RaisePropertyChanged("Causa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
                this.RaisePropertyChanged("Prioridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FrecuenciaCardiaca {
            get {
                return this.frecuenciaCardiacaField;
            }
            set {
                this.frecuenciaCardiacaField = value;
                this.RaisePropertyChanged("FrecuenciaCardiaca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FrecuenciaRespiratoria {
            get {
                return this.frecuenciaRespiratoriaField;
            }
            set {
                this.frecuenciaRespiratoriaField = value;
                this.RaisePropertyChanged("FrecuenciaRespiratoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PresionArterial {
            get {
                return this.presionArterialField;
            }
            set {
                this.presionArterialField = value;
                this.RaisePropertyChanged("PresionArterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SaturacionO2 {
            get {
                return this.saturacionO2Field;
            }
            set {
                this.saturacionO2Field = value;
                this.RaisePropertyChanged("SaturacionO2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Temperatura {
            get {
                return this.temperaturaField;
            }
            set {
                this.temperaturaField = value;
                this.RaisePropertyChanged("Temperatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Dolor {
            get {
                return this.dolorField;
            }
            set {
                this.dolorField = value;
                this.RaisePropertyChanged("Dolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Paciente AuxPaciente {
            get {
                return this.auxPacienteField;
            }
            set {
                this.auxPacienteField = value;
                this.RaisePropertyChanged("AuxPaciente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutPField;
        
        private string pNombreField;
        
        private string sNombreField;
        
        private string apellidoPField;
        
        private string apellidoMField;
        
        private string sexoField;
        
        private System.DateTime fechaNacimientoField;
        
        private string nacionalidadField;
        
        private string anosField;
        
        private string previsionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RutP {
            get {
                return this.rutPField;
            }
            set {
                this.rutPField = value;
                this.RaisePropertyChanged("RutP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PNombre {
            get {
                return this.pNombreField;
            }
            set {
                this.pNombreField = value;
                this.RaisePropertyChanged("PNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SNombre {
            get {
                return this.sNombreField;
            }
            set {
                this.sNombreField = value;
                this.RaisePropertyChanged("SNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApellidoP {
            get {
                return this.apellidoPField;
            }
            set {
                this.apellidoPField = value;
                this.RaisePropertyChanged("ApellidoP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApellidoM {
            get {
                return this.apellidoMField;
            }
            set {
                this.apellidoMField = value;
                this.RaisePropertyChanged("ApellidoM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("FechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("Nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Anos {
            get {
                return this.anosField;
            }
            set {
                this.anosField = value;
                this.RaisePropertyChanged("Anos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Prevision {
            get {
                return this.previsionField;
            }
            set {
                this.previsionField = value;
                this.RaisePropertyChanged("Prevision");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorControlSoapChannel : CapaGUI.ServiceManControl.WebServiceMantenedorControlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorControlSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceManControl.WebServiceMantenedorControlSoap>, CapaGUI.ServiceManControl.WebServiceMantenedorControlSoap {
        
        public WebServiceMantenedorControlSoapClient() {
        }
        
        public WebServiceMantenedorControlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorControlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorControlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorControlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webGuardarControl(CapaGUI.ServiceManControl.Control control, string rutP, string rutM) {
            base.Channel.webGuardarControl(control, rutP, rutM);
        }
        
        public System.Threading.Tasks.Task webGuardarControlAsync(CapaGUI.ServiceManControl.Control control, string rutP, string rutM) {
            return base.Channel.webGuardarControlAsync(control, rutP, rutM);
        }
        
        public System.Data.DataSet webListarHistorial(string rut) {
            return base.Channel.webListarHistorial(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webListarHistorialAsync(string rut) {
            return base.Channel.webListarHistorialAsync(rut);
        }
        
        public CapaGUI.ServiceManControl.Control webListarActivosPantalla(int fila) {
            return base.Channel.webListarActivosPantalla(fila);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManControl.Control> webListarActivosPantallaAsync(int fila) {
            return base.Channel.webListarActivosPantallaAsync(fila);
        }
        
        public CapaGUI.ServiceManControl.Control webListarActivosPantallaReceta(int fila) {
            return base.Channel.webListarActivosPantallaReceta(fila);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceManControl.Control> webListarActivosPantallaRecetaAsync(int fila) {
            return base.Channel.webListarActivosPantallaRecetaAsync(fila);
        }
        
        public System.Data.DataSet webListarActivos() {
            return base.Channel.webListarActivos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webListarActivosAsync() {
            return base.Channel.webListarActivosAsync();
        }
        
        public System.Data.DataSet webListarActivosReceta() {
            return base.Channel.webListarActivosReceta();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webListarActivosRecetaAsync() {
            return base.Channel.webListarActivosRecetaAsync();
        }
    }
}
